name: Build and Test

on:
  push:
    branches: [ "develop", "feature" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore deps
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Run unit and integration tests
      run: dotnet test --no-build --verbosity normal
